# Site settings
name: Raphael Medeiros
description: "Software Engineer, Father, and Consultant in Natal, RN, Brazil"
url: "https://byraphaelmedeiros.github.io/"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  byraphaelmedeiros
#codepen_username: your_codepen_username_goes_here
#facebook_username: your_facebook_username_goes_here
#vk_username: your_vk_username_goes_here
#twitter_username: your_twitter_username_goes_here
#google_plus_username: your_google_plus_username_goes_here
linkedin_username: raphaelmedeiros
#vine_username:  your_vine_username_goes_here
#instagram_username:  your_instagram_username_goes_here
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
#soundcloud_username:  your_soundcloud_username_goes_here
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#lastfm_username: your_lastfm_username_goes_here
www_url: "https://www.byraphaelmedeiros.com/"
#blog_url: "https://www.pontonulo.com.br/"
#email: raphael.medeiros@gmail.com
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/1038492"


front_img: yes
#front_img_path: "imgs/background.jpg"
front_img_path: "https://i.pinimg.com/originals/e0/ad/78/e0ad783170137c9587414cef9cb4752d.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
